//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ürün_Mensegini_Bulma.svr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.gepir.org.tr/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gepir.org.tr/", ConfigurationName="svr.AndroidSoap")]
    public interface AndroidSoap {
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://www.gepir.org.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchByGTIN", ReplyAction="*")]
        Ürün_Mensegini_Bulma.svr.SearchByGTINResponse SearchByGTIN(Ürün_Mensegini_Bulma.svr.SearchByGTINRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchByGTIN", ReplyAction="*")]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByGTINResponse> SearchByGTINAsync(Ürün_Mensegini_Bulma.svr.SearchByGTINRequest request);
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://www.gepir.org.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchByGLN", ReplyAction="*")]
        Ürün_Mensegini_Bulma.svr.SearchByGLNResponse SearchByGLN(Ürün_Mensegini_Bulma.svr.SearchByGLNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchByGLN", ReplyAction="*")]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByGLNResponse> SearchByGLNAsync(Ürün_Mensegini_Bulma.svr.SearchByGLNRequest request);
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://www.gepir.org.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchBySSCC", ReplyAction="*")]
        Ürün_Mensegini_Bulma.svr.SearchBySSCCResponse SearchBySSCC(Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchBySSCC", ReplyAction="*")]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchBySSCCResponse> SearchBySSCCAsync(Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest request);
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://www.gepir.org.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchByName", ReplyAction="*")]
        Ürün_Mensegini_Bulma.svr.SearchByNameResponse SearchByName(Ürün_Mensegini_Bulma.svr.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByNameResponse> SearchByNameAsync(Ürün_Mensegini_Bulma.svr.SearchByNameRequest request);
        
        // CODEGEN: Generating message contract since element name sUserName from namespace http://www.gepir.org.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/Login", ReplyAction="*")]
        Ürün_Mensegini_Bulma.svr.LoginResponse Login(Ürün_Mensegini_Bulma.svr.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gepir.org.tr/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.LoginResponse> LoginAsync(Ürün_Mensegini_Bulma.svr.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByGTINRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByGTIN", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchByGTINRequestBody Body;
        
        public SearchByGTINRequest() {
        }
        
        public SearchByGTINRequest(Ürün_Mensegini_Bulma.svr.SearchByGTINRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchByGTINRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPremiumName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sPremiumPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sGTIN;
        
        public SearchByGTINRequestBody() {
        }
        
        public SearchByGTINRequestBody(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sGTIN) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sPremiumName = sPremiumName;
            this.sPremiumPassword = sPremiumPassword;
            this.sGTIN = sGTIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByGTINResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByGTINResponse", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchByGTINResponseBody Body;
        
        public SearchByGTINResponse() {
        }
        
        public SearchByGTINResponse(Ürün_Mensegini_Bulma.svr.SearchByGTINResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchByGTINResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByGTINResult;
        
        public SearchByGTINResponseBody() {
        }
        
        public SearchByGTINResponseBody(Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByGTINResult) {
            this.SearchByGTINResult = SearchByGTINResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByGLNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByGLN", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchByGLNRequestBody Body;
        
        public SearchByGLNRequest() {
        }
        
        public SearchByGLNRequest(Ürün_Mensegini_Bulma.svr.SearchByGLNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchByGLNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPremiumName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sPremiumPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sGLN;
        
        public SearchByGLNRequestBody() {
        }
        
        public SearchByGLNRequestBody(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sGLN) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sPremiumName = sPremiumName;
            this.sPremiumPassword = sPremiumPassword;
            this.sGLN = sGLN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByGLNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByGLNResponse", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchByGLNResponseBody Body;
        
        public SearchByGLNResponse() {
        }
        
        public SearchByGLNResponse(Ürün_Mensegini_Bulma.svr.SearchByGLNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchByGLNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByGLNResult;
        
        public SearchByGLNResponseBody() {
        }
        
        public SearchByGLNResponseBody(Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByGLNResult) {
            this.SearchByGLNResult = SearchByGLNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchBySSCCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchBySSCC", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchBySSCCRequestBody Body;
        
        public SearchBySSCCRequest() {
        }
        
        public SearchBySSCCRequest(Ürün_Mensegini_Bulma.svr.SearchBySSCCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchBySSCCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPremiumName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sPremiumPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sSSCC;
        
        public SearchBySSCCRequestBody() {
        }
        
        public SearchBySSCCRequestBody(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sSSCC) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sPremiumName = sPremiumName;
            this.sPremiumPassword = sPremiumPassword;
            this.sSSCC = sSSCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchBySSCCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchBySSCCResponse", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchBySSCCResponseBody Body;
        
        public SearchBySSCCResponse() {
        }
        
        public SearchBySSCCResponse(Ürün_Mensegini_Bulma.svr.SearchBySSCCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchBySSCCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchBySSCCResult;
        
        public SearchBySSCCResponseBody() {
        }
        
        public SearchBySSCCResponseBody(Ürün_Mensegini_Bulma.svr.ArrayOfString SearchBySSCCResult) {
            this.SearchBySSCCResult = SearchBySSCCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByName", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchByNameRequestBody Body;
        
        public SearchByNameRequest() {
        }
        
        public SearchByNameRequest(Ürün_Mensegini_Bulma.svr.SearchByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPremiumName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sPremiumPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string streetAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string postalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string country;
        
        public SearchByNameRequestBody() {
        }
        
        public SearchByNameRequestBody(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string companyName, string city, string streetAddress, string postalCode, string country) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sPremiumName = sPremiumName;
            this.sPremiumPassword = sPremiumPassword;
            this.companyName = companyName;
            this.city = city;
            this.streetAddress = streetAddress;
            this.postalCode = postalCode;
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByNameResponse", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.SearchByNameResponseBody Body;
        
        public SearchByNameResponse() {
        }
        
        public SearchByNameResponse(Ürün_Mensegini_Bulma.svr.SearchByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class SearchByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByNameResult;
        
        public SearchByNameResponseBody() {
        }
        
        public SearchByNameResponseBody(Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByNameResult) {
            this.SearchByNameResult = SearchByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Ürün_Mensegini_Bulma.svr.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sPremiumName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sPremiumPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sDescription;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sDescription) {
            this.sUserName = sUserName;
            this.sPassword = sPassword;
            this.sPremiumName = sPremiumName;
            this.sPremiumPassword = sPremiumPassword;
            this.sDescription = sDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://www.gepir.org.tr/", Order=0)]
        public Ürün_Mensegini_Bulma.svr.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Ürün_Mensegini_Bulma.svr.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gepir.org.tr/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ürün_Mensegini_Bulma.svr.ArrayOfString LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(Ürün_Mensegini_Bulma.svr.ArrayOfString LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AndroidSoapChannel : Ürün_Mensegini_Bulma.svr.AndroidSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AndroidSoapClient : System.ServiceModel.ClientBase<Ürün_Mensegini_Bulma.svr.AndroidSoap>, Ürün_Mensegini_Bulma.svr.AndroidSoap {
        
        public AndroidSoapClient() {
        }
        
        public AndroidSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AndroidSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AndroidSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AndroidSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ürün_Mensegini_Bulma.svr.SearchByGTINResponse Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchByGTIN(Ürün_Mensegini_Bulma.svr.SearchByGTINRequest request) {
            return base.Channel.SearchByGTIN(request);
        }
        
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByGTIN(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sGTIN) {
            Ürün_Mensegini_Bulma.svr.SearchByGTINRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchByGTINRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchByGTINRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sGTIN = sGTIN;
            Ürün_Mensegini_Bulma.svr.SearchByGTINResponse retVal = ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchByGTIN(inValue);
            return retVal.Body.SearchByGTINResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByGTINResponse> Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchByGTINAsync(Ürün_Mensegini_Bulma.svr.SearchByGTINRequest request) {
            return base.Channel.SearchByGTINAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByGTINResponse> SearchByGTINAsync(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sGTIN) {
            Ürün_Mensegini_Bulma.svr.SearchByGTINRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchByGTINRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchByGTINRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sGTIN = sGTIN;
            return ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchByGTINAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ürün_Mensegini_Bulma.svr.SearchByGLNResponse Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchByGLN(Ürün_Mensegini_Bulma.svr.SearchByGLNRequest request) {
            return base.Channel.SearchByGLN(request);
        }
        
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByGLN(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sGLN) {
            Ürün_Mensegini_Bulma.svr.SearchByGLNRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchByGLNRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchByGLNRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sGLN = sGLN;
            Ürün_Mensegini_Bulma.svr.SearchByGLNResponse retVal = ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchByGLN(inValue);
            return retVal.Body.SearchByGLNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByGLNResponse> Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchByGLNAsync(Ürün_Mensegini_Bulma.svr.SearchByGLNRequest request) {
            return base.Channel.SearchByGLNAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByGLNResponse> SearchByGLNAsync(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sGLN) {
            Ürün_Mensegini_Bulma.svr.SearchByGLNRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchByGLNRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchByGLNRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sGLN = sGLN;
            return ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchByGLNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ürün_Mensegini_Bulma.svr.SearchBySSCCResponse Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchBySSCC(Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest request) {
            return base.Channel.SearchBySSCC(request);
        }
        
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchBySSCC(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sSSCC) {
            Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchBySSCCRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sSSCC = sSSCC;
            Ürün_Mensegini_Bulma.svr.SearchBySSCCResponse retVal = ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchBySSCC(inValue);
            return retVal.Body.SearchBySSCCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchBySSCCResponse> Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchBySSCCAsync(Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest request) {
            return base.Channel.SearchBySSCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchBySSCCResponse> SearchBySSCCAsync(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sSSCC) {
            Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchBySSCCRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchBySSCCRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sSSCC = sSSCC;
            return ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchBySSCCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ürün_Mensegini_Bulma.svr.SearchByNameResponse Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchByName(Ürün_Mensegini_Bulma.svr.SearchByNameRequest request) {
            return base.Channel.SearchByName(request);
        }
        
        public Ürün_Mensegini_Bulma.svr.ArrayOfString SearchByName(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string companyName, string city, string streetAddress, string postalCode, string country) {
            Ürün_Mensegini_Bulma.svr.SearchByNameRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchByNameRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchByNameRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.companyName = companyName;
            inValue.Body.city = city;
            inValue.Body.streetAddress = streetAddress;
            inValue.Body.postalCode = postalCode;
            inValue.Body.country = country;
            Ürün_Mensegini_Bulma.svr.SearchByNameResponse retVal = ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchByName(inValue);
            return retVal.Body.SearchByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByNameResponse> Ürün_Mensegini_Bulma.svr.AndroidSoap.SearchByNameAsync(Ürün_Mensegini_Bulma.svr.SearchByNameRequest request) {
            return base.Channel.SearchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.SearchByNameResponse> SearchByNameAsync(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string companyName, string city, string streetAddress, string postalCode, string country) {
            Ürün_Mensegini_Bulma.svr.SearchByNameRequest inValue = new Ürün_Mensegini_Bulma.svr.SearchByNameRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.SearchByNameRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.companyName = companyName;
            inValue.Body.city = city;
            inValue.Body.streetAddress = streetAddress;
            inValue.Body.postalCode = postalCode;
            inValue.Body.country = country;
            return ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).SearchByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ürün_Mensegini_Bulma.svr.LoginResponse Ürün_Mensegini_Bulma.svr.AndroidSoap.Login(Ürün_Mensegini_Bulma.svr.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Ürün_Mensegini_Bulma.svr.ArrayOfString Login(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sDescription) {
            Ürün_Mensegini_Bulma.svr.LoginRequest inValue = new Ürün_Mensegini_Bulma.svr.LoginRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.LoginRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sDescription = sDescription;
            Ürün_Mensegini_Bulma.svr.LoginResponse retVal = ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.LoginResponse> Ürün_Mensegini_Bulma.svr.AndroidSoap.LoginAsync(Ürün_Mensegini_Bulma.svr.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ürün_Mensegini_Bulma.svr.LoginResponse> LoginAsync(string sUserName, string sPassword, string sPremiumName, string sPremiumPassword, string sDescription) {
            Ürün_Mensegini_Bulma.svr.LoginRequest inValue = new Ürün_Mensegini_Bulma.svr.LoginRequest();
            inValue.Body = new Ürün_Mensegini_Bulma.svr.LoginRequestBody();
            inValue.Body.sUserName = sUserName;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sPremiumName = sPremiumName;
            inValue.Body.sPremiumPassword = sPremiumPassword;
            inValue.Body.sDescription = sDescription;
            return ((Ürün_Mensegini_Bulma.svr.AndroidSoap)(this)).LoginAsync(inValue);
        }
    }
}
